In [22]:
import pylatex

# Processo de ramificação

$p_k = e^{-\theta} \frac{\theta^k}{k!}$, k = 0,1,2,...

onde $\theta$ é um parâmetro positivo e vamos considerar 2 casos: $\theta = 0,n_1$ e $\theta = 2,n_1$

$n_1$ é o último dígito diferente de 0 do meu nUSP, nesse caso 2. 

NUSP:3759732

## Simular os 20 primeiros passos do processo nos dois seguintes casos, com $X_0 = 10$

In [1]:
import numpy as np
import math

def p(theta, k):
    pk = np.exp(-theta) * ((math.pow(theta,k))/(np.math.factorial(k)))
    return pk


def ramificacao(M, X, theta):
    n = 0
    print("Inicio: ")
    while (X[n] != 0 and n <= (M - 1)):
        n += 1
        print("{} ".format(n), end="", flush=True)
        j = 1
        X[n] = 0
        while (j <= X[n - 1]):
            U = np.random.uniform()
            i = 0
            soma = p(theta, i)
            while (U >= soma):
                i += 1
                soma += p(theta, i)

            X[n] += i
            j += 1

## Corrigido

In [43]:
def _poisson(k, theta):
    aux = np.math.pow(theta,k) * np.math.exp(-theta)/np.math.factorial(k)
    return aux 

def _ramificacao(M, X, theta):
    i = 0
    print("Inicio: ")
    while (X[i] != 0 and i <= (M - 1)):
        i += 1
        print("{} ".format(i), end="", flush=True)
        j = 1
        while (j <= X[i - 1]):
            n = 0
            U = np.random.uniform()
            p = _poisson(0,theta)
            while ( U >= p ) :
                n = n + 1
                p = p + _poisson(n,theta)
        
            X[i] = n
            j += 1

In [29]:
r1 = np.zeros(21, int)
r1[0] = 10

In [30]:
ramificacao(20,r1,0.2)

Inicio: 1
Inicio: 2
Inicio: 3
Inicio: 4


In [31]:
r1

array([10,  6,  2,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0])

In [32]:
r2 = np.zeros(21,int)
r2[0] = 10


In [33]:
ramificacao(20,r2,2.2)

Inicio: 1
Inicio: 2
Inicio: 3
Inicio: 4
Inicio: 5
Inicio: 6
Inicio: 7
Inicio: 8
Inicio: 9
Inicio: 10
Inicio: 11
Inicio: 12
Inicio: 13
Inicio: 14
Inicio: 15
Inicio: 16
Inicio: 17
Inicio: 18
Inicio: 19
Inicio: 20


In [34]:
r2

array([      10,       16,       38,       87,      187,      423,
            872,     1849,     4042,     8669,    19221,    42238,
          92611,   203959,   448243,   987544,  2172805,  4779951,
       10516057, 23134240, 50890072])

## Corrigido

In [42]:
print("Corrigido")

r1 = np.zeros(21, int)
r1[0] = 10

_ramificacao(20,r1,0.2)

print(r1)

r2 = np.zeros(21,int)
r2[0] = 10

_ramificacao(20,r2,2.2)

print(r2)



Corrigido
Inicio: 
1 [10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
Inicio: 
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 [10  5  5  2  2  4  5  1  2  2  1  4  3  4  2  4  2  3  2  4  3]


Isso não bate com a teoria, explicações no final.

## Para os dois casos diga o que puder sobre o limite:
$\lim_{n to \infty} P(X_n \geq 1| X_0 = 10)$

### Para o primeiro caso, onde $\theta = 0.2$, $X_n$ vai rapidamente a 0. Assim,  $P(X_n \geq 1| X_0 = 10)$ quando n vai para o infinito é 0.
No caso onde $\theta = 2.2$, ocorre o contrário, o valor cresce e $X_n$ vai ser sempre maior que 1 quando o n for a infinito.

Com isso, poderíamos ter uma ideia da grandeza do valor de $E(X_{20})$.
$E(X_n|X_0 = 10) = 10 (kp)^n$
No caso da Poisson, temos que este valor é igual a $\theta$.
Desta maneira, para o $\theta = 0.2$, teríamos: $10 * (0,2)^{20} = 1,048x10^{-13}$; para $\theta = 2.2$, teríamos: $10 * (2,2)^{20} = 7,05x10^7$. Portanto, os meus resultados correspondem à grandeza esperada.

# Epidemia

$q_k = (1 - \alpha) \alpha^k, k = 0,1,2,...$,
onde, $\alpha \in (0,1)$


Vamos considerar dois casos: $\alpha = 0,9$ e $p = 0,n_2$ e $\alpha = 0,1$ e $p = 0,n_2$

Sendo $n_2$ o penúltimo dígito diferente de 0 do meu nUSP, aqui 0,3.

## Processo de epidemia com número aleatório

In [19]:
def qk(alpha, k):
    q = (1-alpha)*math.pow(alpha,k)
    return q

def epidemia(M,X,alpha,p):
    n = 0 
    while (X[n]!=0 and n<=M-1):
        n += 1
        print("Inicio: {}".format(n))
        X[n] = 0
        for i in range(X[n-1]):
            k = 0 #número de contatos
            u = np.random.uniform()
            #print("u1 {}".format(u))
            contatos = qk(alpha, k)
            while(u>=contatos):
                k += 1
                contatos += qk(alpha, k)
            s = 0 
            j = 0
            for j in range(k):
                u = np.random.uniform()
                #print("u2 {}".format(u))
                if(u<=p):
                    s += 1
            X[n] += s
            #print("X[{}] = {}".format(n, X[n]))         


## Simular 20 passos do algoritmo para ambos os casos, com $X_0 = 10$.

In [46]:
e1 = np.zeros(21, int)
e1[0] = 10

In [47]:
epidemia(20,e1,0.9,0.3)

Inicio: 1
Inicio: 2
Inicio: 3
Inicio: 4
Inicio: 5
Inicio: 6
Inicio: 7
Inicio: 8
Inicio: 9
Inicio: 10
Inicio: 11
Inicio: 12
Inicio: 13
Inicio: 14
Inicio: 15
Inicio: 16
Inicio: 17
Inicio: 18
Inicio: 19
Inicio: 20


KeyboardInterrupt: 

In [48]:
e1

array([       10,        13,        23,        34,        73,       210,
             593,      1645,      4413,     11968,     32217,     86896,
          234696,    635382,   1714162,   4624559,  12484927,  33725465,
        91069195, 245882310, 229119208])

In [49]:
e2 = np.zeros(20,int)
e2[0] = 10

In [50]:
epidemia(21,e2,0.1,0.3)

Inicio: 1
Inicio: 2


In [51]:
e2

array([10,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0])

## Para ambos os casos calcular o seguinte:
$\lim_{n to \infty} P(X_n \geq 1| X_0 = 10)$

Para o primeiro caso, onde nosso $\alpha = 0.9$ depois o valor de $X_n$ cresce rapidamente, assim o limite é 1, a $P(X_n \geq 1| X_0 = 10)$ quando n tende a infinito é 1.
Já, no segundo caso, nosso $\alpha = 0.1$, fazendo com que o número de contatos seja menor, e mantemos a probabilidade de infecção igual. Dessa maneira, quando n tende a infinito a $P(X_n \geq 1| X_0 = 10)$ é 0.

## Correções
Modifiquei o algorítimo segundo o algorítimo da correção e foram encontrados valores discrepantes para o item 2, pois o algorítimo da resolução implementado acaba indo pra zero mesmo para theta "grade" (2.2). Acredito que a implementação da correção possa estar errada e a minha resposta está certa pois segue junto a teoria.
Portando acredito que o item 1, 2 e 3 estejam corretos.

No item 4 o cálculo do limite está incorreto segundo a resolução, mas não consegui corrigir. 

No item 5 está correto.

No item 6 foi melhorado.

No item 7 está correto.